
name: Non OMV based tests

on:
  push:
    branches: [ master, development, experimental, "*test*" ]
  pull_request:
    branches: [ master, development, experimental, "*test*" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7, 3.9 ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Run scripts
      run: |
        pip install pyneuroml
        cd NeuroML2
        python pyr_soma_cell.py
        ls -alt

    - name: Final version info
      run: |
        pip list
